### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by bharatkrishna** [povilasb/quic-version-detector#2]
I installed quic-version-detector using pip: `sudo pip install quic-version-detector`

It complained asyncio module was not found: `ImportError: No module named asyncio`.

I installed asynicio using pip: `sudo pip install asyncio`

I get a syntax error when I run this tool:

```
$ quicver google.com 443
Traceback (most recent call last):
  File "/usr/local/bin/quicver", line 9, in <module>
    load_entry_point('quic-version-detector==0.2.0', 'console_scripts', 'quicver')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2184, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/quic_version_detector/main.py", line 2, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

I am on Ubuntu 14.04.4 LTS. 
Python version: 2.7.6

**Comment by povilasb** [comment]
The tool only works with python 3.

**Comment by bharatkrishna** [comment]
`/usr/bin/python` was python 2 on my machine. `/usr/bin/python3` is Python 3.4.3.

I edited `/usr/local/bin/quicver` and replaced python with python3 in the shebang(`#!/usr/bin/python3`).

I get a different error:

```
$  quicver google.com 443
Traceback (most recent call last):
  File "/usr/local/bin/quicver", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: quic-version-detector==0.1.2
```

Would there be any other place I should be doing this change ?

**Comment by povilasb** [comment]
Well python3 packages have a different path in the system.
So you should use `pip3` to install the package.
E.g. `pip3 install quic-version-detector`.
